name: Build HTML on S3
on:
  pull_request:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2  # リポジトリをチェックアウト

      - name: Deploy  # S3にデプロイ 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      
      - name: Copy file to the development website with the AWS CLI
        run: |
          aws s3 sync --delete ./ s3://shimi-lynx-s3-deploy-test